```{r}
# The aim of this script is to describe TE driven eccDNA in Illumina mobilome sample

# Load librairies 
library(stringr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(plotly)
library(pheatmap)
library(tidyverse)
library(DESeq2)

# Read intial TE annotation, new TE clustering file with correpsonding TE family and cluster, and table with average size of copies
setwd("/media/lgdp/TOSHIBA/Verzy/Mobilome_Verzy/")
cluster=read.table(file="/home/lgdp/Desktop/FsylCur4_last_annotation_data/FsylCur4_denovoLibTEs_cluster.fa.clustr")
size=read.table(file="/home/lgdp/Desktop/FsylCur4_last_annotation_data/FsylCur4_denovoLibTEs_size.txt")
te_fam=read.table(file="/media/lgdp/TOSHIBA/Verzy/Mobilome_Verzy/Resultats_eccFinder_Mapping/ecc.sr.sorted-TEs.txt")
family=unique(data.frame(str_split_fixed(te_fam$V1, "_", 4)))

# Merge and format table
te_fam=left_join(family,cluster,by=c("X4"="V1"))
te_fam$name=paste0(te_fam$X1,"_",te_fam$V2)
te_fam$id=paste0(te_fam$X1,"_",te_fam$X2,"_",te_fam$X3,"_",te_fam$X4)
te_fam=left_join(te_fam,size,by=c("X4"="V1"))

te_fam=unique(te_fam[,c(6:8)])
te_fam_moy= te_fam %>% group_by(name) %>%summarise(mean = mean(V2.y))
te_fam=left_join(te_fam,te_fam_moy,by=c("name"="name"))
te_fam$name=sub("\\|NA","",te_fam$name)
te_fam$name=sub("helitron","Helitron",te_fam$name)
te_fam$name=sub("\\|MITE","",te_fam$name)
te_fam=te_fam[,-c(3)]

```



```{r}

# Read coverage table of with read depth per TE locus
bed=read.table(file="ecc.sr.sorted_185M-TEs.bed")
# Remove small peaks
bed$size=bed$V3-bed$V2
bed=bed[bed$size>=100,]
data_rc=bed[,c(4,5)]

# Sum locus coverage by TE family
data_rc=data_rc %>%group_by(V5) %>% dplyr::mutate(allRC_count = sum(V4))
data_rc=unique(data_rc[,c(2,3)])

# Sum read depth by TE cluster
data_rc=left_join(data_rc,te_fam,by=c("V5"="id"))
data_rc=data_rc %>%group_by(name) %>% dplyr::mutate(allRC_count2 = sum(allRC_count))
data_rc=data_rc[,c(3:5)]
data_rc=na.omit(data_rc)
data_185M=unique(data_rc)


bed=read.table(file="ecc.sr.sorted_185R-TEs.bed")
bed$size=bed$V3-bed$V2
bed=bed[bed$size>=100,]
data_rc=bed[,c(4,5)]
data_rc=data_rc %>%group_by(V5) %>% dplyr::mutate(allRC_count = sum(V4))
data_rc=unique(data_rc[,c(2,3)])
data_rc=left_join(data_rc,te_fam,by=c("V5"="id"))
data_rc=data_rc %>%group_by(name) %>% dplyr::mutate(allRC_count2 = sum(allRC_count))
data_rc=data_rc[,c(3:5)]
data_rc=na.omit(data_rc)
data_185R=data_rc


bed=read.table(file="ecc.sr.sorted_194M-TEs.bed")
bed$size=bed$V3-bed$V2
bed=bed[bed$size>=100,]
data_rc=bed[,c(4,5)]
data_rc=data_rc %>%group_by(V5) %>% dplyr::mutate(allRC_count = sum(V4))
data_rc=unique(data_rc[,c(2,3)])
data_rc=left_join(data_rc,te_fam,by=c("V5"="id"))
data_rc=data_rc %>%group_by(name) %>% dplyr::mutate(allRC_count2 = sum(allRC_count))
data_rc=data_rc[,c(3:5)]
data_rc=na.omit(data_rc)
data_194M=data_rc


bed=read.table(file="ecc.sr.sorted_194R-TEs.bed")
bed$size=bed$V3-bed$V2
bed=bed[bed$size>=100,]
data_rc=bed[,c(4,5)]
data_rc=data_rc %>%group_by(V5) %>% dplyr::mutate(allRC_count = sum(V4))
data_rc=unique(data_rc[,c(2,3)])
data_rc=left_join(data_rc,te_fam,by=c("V5"="id"))
data_rc=data_rc %>%group_by(name) %>% dplyr::mutate(allRC_count2 = sum(allRC_count))
data_rc=data_rc[,c(3:5)]
data_rc=na.omit(data_rc)
data_194R=data_rc


bed=read.table(file="ecc.sr.sorted_216M-TEs.bed")
bed$size=bed$V3-bed$V2
bed=bed[bed$size>=100,]
data_rc=bed[,c(4,5)]
data_rc=data_rc %>%group_by(V5) %>% dplyr::mutate(allRC_count = sum(V4))
data_rc=unique(data_rc[,c(2,3)])
data_rc=left_join(data_rc,te_fam,by=c("V5"="id"))
data_rc=data_rc %>%group_by(name) %>% dplyr::mutate(allRC_count2 = sum(allRC_count))
data_rc=data_rc[,c(3:5)]
data_rc=na.omit(data_rc)
data_216M=data_rc


bed=read.table(file="ecc.sr.sorted_216R-TEs.bed")
bed$size=bed$V3-bed$V2
bed=bed[bed$size>=100,]
data_rc=bed[,c(4,5)]
data_rc=data_rc %>%group_by(V5) %>% dplyr::mutate(allRC_count = sum(V4))
data_rc=unique(data_rc[,c(2,3)])
data_rc=left_join(data_rc,te_fam,by=c("V5"="id"))
data_rc=data_rc %>%group_by(name) %>% dplyr::mutate(allRC_count2 = sum(allRC_count))
data_rc=data_rc[,c(3:5)]
data_rc=na.omit(data_rc)
data_216R=data_rc


bed=read.table(file="ecc.sr.sorted_354M-TEs.bed")
bed$size=bed$V3-bed$V2
bed=bed[bed$size>=100,]
data_rc=bed[,c(4,5)]
data_rc=data_rc %>%group_by(V5) %>% dplyr::mutate(allRC_count = sum(V4))
data_rc=unique(data_rc[,c(2,3)])
data_rc=left_join(data_rc,te_fam,by=c("V5"="id"))
data_rc=data_rc %>%group_by(name) %>% dplyr::mutate(allRC_count2 = sum(allRC_count))
data_rc=data_rc[,c(3:5)]
data_rc=na.omit(data_rc)
data_354M=data_rc


bed=read.table(file="ecc.sr.sorted_354R-TEs.bed")
bed$size=bed$V3-bed$V2
bed=bed[bed$size>=100,]
data_rc=bed[,c(4,5)]
data_rc=data_rc %>%group_by(V5) %>% dplyr::mutate(allRC_count = sum(V4))
data_rc=unique(data_rc[,c(2,3)])
data_rc=left_join(data_rc,te_fam,by=c("V5"="id"))
data_rc=data_rc %>%group_by(name) %>% dplyr::mutate(allRC_count2 = sum(allRC_count))
data_rc=data_rc[,c(3:5)]
data_rc=na.omit(data_rc)
data_354R=data_rc


bed=read.table(file="ecc.sr.sorted_525M-TEs.bed")
bed$size=bed$V3-bed$V2
bed=bed[bed$size>=100,]
data_rc=bed[,c(4,5)]
data_rc=data_rc %>%group_by(V5) %>% dplyr::mutate(allRC_count = sum(V4))
data_rc=unique(data_rc[,c(2,3)])
data_rc=left_join(data_rc,te_fam,by=c("V5"="id"))
data_rc=data_rc %>%group_by(name) %>% dplyr::mutate(allRC_count2 = sum(allRC_count))
data_rc=data_rc[,c(3:5)]
data_rc=na.omit(data_rc)
data_525M=data_rc


bed=read.table(file="ecc.sr.sorted_525R-TEs.bed")
bed$size=bed$V3-bed$V2
bed=bed[bed$size>=100,]
data_rc=bed[,c(4,5)]
data_rc=data_rc %>%group_by(V5) %>% dplyr::mutate(allRC_count = sum(V4))
data_rc=unique(data_rc[,c(2,3)])
data_rc=left_join(data_rc,te_fam,by=c("V5"="id"))
data_rc=data_rc %>%group_by(name) %>% dplyr::mutate(allRC_count2 = sum(allRC_count))
data_rc=data_rc[,c(3:5)]
data_rc=na.omit(data_rc)
data_525R=data_rc
```




```{r}
# Retrive all TE families found in eccDNA samples
TE=unique(rbind(data_185M$name,data_185R$name,data_194M$name,data_194R$name,data_216M$name,data_216R$name,data_354M$name,data_354R$name,data_525M$name,data_525R$name))
TE=unique(data.frame(c(t(TE))))
colnames(TE)="V4.x"

# merge all data with TE family name as an ID to obtain a coverage table across sample
data=left_join(TE,data_185M,by=c("V4.x"="name"))
data=left_join(data,data_185R,by=c("V4.x"="name"))

data=left_join(data,data_194M,by=c("V4.x"="name"))
data=left_join(data,data_194R,by=c("V4.x"="name"))

data=left_join(data,data_216M,by=c("V4.x"="name"))
data=left_join(data,data_216R,by=c("V4.x"="name"))

data=left_join(data,data_354M,by=c("V4.x"="name"))
data=left_join(data,data_354R,by=c("V4.x"="name"))

data=left_join(data,data_525M,by=c("V4.x"="name"))
data=left_join(data,data_525R,by=c("V4.x"="name"))

# Format data frame
data[is.na(data)] <- 0
data=unique(data)
data=data[,-c(2,4,6,8,10,12,14,16,18,20)]
data=data %>% group_by(V4.x) %>% summarise(across(everything(), sum))
data=left_join(data,unique(te_fam[,c(1,3)]),by=c("V4.x"="name"))

# rename columns
colnames(data)=c("TE","X185M","X185R","X194M","X194R","X216M","X216R","X354M","X354R","X525M","X525R","size")
data_rd_sr=data[,-c(12)]

# Normalize by mean size of copies
data=data[data$TE!="LTR_NA",]
data=data.frame(unique(data))
data$X185M=data$X185M/data$size
data$X185R=data$X185R/data$size

data$X194M=data$X194M/data$size
data$X194R=data$X194R/data$size

data$X216M=data$X216M/data$size
data$X216R=data$X216R/data$size

data$X354M=data$X354M/data$size
data$X354R=data$X354R/data$size

data$X525M=data$X525M/data$size
data$X525R=data$X525R/data$size
data=data[,-c(12)]

# Normalize by library size
data$X185M=data$X185M/2.472845
data$X185R=data$X185R/2.301978
data$X194M=data$X194M/1.898806
data$X194R=data$X194R/2.495862
data$X216M=data$X216M/1.948078
data$X216R=data$X216R/3.081593
data$X354M=data$X354M/0.412066
data$X354R=data$X354R/1.686393
data$X525M=data$X525M/2.223802
data$X525R=data$X525R/1.405007

# Format and filter matrix
data=data %>% remove_rownames() %>% column_to_rownames(var = 'TE')
data=data[(data$X185M>0 | data$X185R>0 | data$X194M>0 | data$X194R>0 | data$X216M>0 | data$X216R>0 | data$X354M>0 | data$X354R>0 | data$X525M>0 | data$X525R>0), ]

# Scale matrix
data$X185M=scale(data$X185M)
data$X185R=scale(data$X185R)
data$X194M=scale(data$X194M)
data$X194R=scale(data$X194R)
data$X216M=scale(data$X216M)
data$X216R=scale(data$X216R)
data$X354M=scale(data$X354M)
data$X354R=scale(data$X354R)
data$X525M=scale(data$X525M)
data$X525R=scale(data$X525R)

mtscaled_sr <- as.matrix(data)
colnames(mtscaled_sr)=c("sr_185M","sr_185R","sr_194M","sr_194R","sr_216M","sr_216R","sr_354M","sr_354R","sr_525M","sr_525R")
mtscaled_sr<-mtscaled_sr[order(rownames(mtscaled_sr)),]
hmcols<-colorRampPalette(c("white","#de3e51", "#962483"))(10)

# Plot heatmap
png("heatmap_eccdna_sr_verzy.png",res=800,width=6000,height = 17000)
pheatmap(mtscaled_sr,cluster_rows = T,rot = 45,cluster_cols = T, fontsize_row =2.5, fontsize_col = 10, margins=c(7,3),color=hmcols,legend_labels =T)
```


